version: '3'

services:
  mongo:
    container_name: mongo
    image: mongo:4.2.1-bionic
    restart: always
    ports:
      - "27018:27017"
    networks:
      - backend

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - backend
          
  app:
    container_name: ts-node-app
    build: 
      context: .
      dockerfile: Dockerfile
      target: base
    restart: always
    env_file: .env
    expose:
      - ${PORT}
    ports:
      - ${PORT}:${PORT}
    environment: 
      - MONGODB_URL=mongodb://mongo:27017/users-list
      - CLIENT_URL=${CLIENT_URL}
    links: 
      - mongo  
    depends_on:
      - mongo  
    networks:
      - backend

networks:
  backend:
    driver: bridge    
